/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gosuncn_zfyfw_nv_NvUtilExt */

#ifndef _Included_com_gosuncn_zfyfw_nv_NvUtilExt
#define _Included_com_gosuncn_zfyfw_nv_NvUtilExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gosuncn_zfyfw_nv_NvUtilExt
 * Method:    nativeNvRead
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gosuncn_zfyfw_nv_NvUtilExt_nativeNvRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gosuncn_zfyfw_nv_NvUtilExt
 * Method:    nativeNvWrite
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gosuncn_zfyfw_nv_NvUtilExt_nativeNvWrite
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
